### ISSUE TITLE
Conversion labelbox json to COCO json

### ISSUE THREAD

**Issue by maxsenh** [Labelbox/Labelbox#152]
Hi
I was trying to convert a labelbox json file to a coco-style json file with labelbox2coco. It raised the error
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-d1c853b2aed3> in <module>
----> 1 lb2co.from_json(labeled_data = box, coco_output = coco_out)

~/anaconda3/envs/mrcnn_b/lib/python3.6/site-packages/labelbox2coco/__init__.py in from_json(labeled_data, coco_output)
     84                 polygons = wkt.loads(wkt_data)
     85 
---> 86             for polygon in polygons:
     87                 segmentation = []
     88                 for x, y in polygon.exterior.coords:

~/anaconda3/envs/mrcnn_b/lib/python3.6/site-packages/labelbox2coco/__init__.py in <lambda>(x)
     80 
     81             if type(wkt_data) is list:
---> 82                 polygons = map(lambda x: wkt.loads(x['geometry']), wkt_data)
     83             else:
     84                 polygons = wkt.loads(wkt_data)

TypeError: list indices must be integers or slices, not str
```
For some reason my file format does not fit the conversion script. When I print wkt_data, it gives me coordinates. Does this problem sound familiar? I have not found any help in the Issue section. Printing dict_keys gives this:
```python
dict_keys(['ID', 'Labeled Data', 'Label', 'Created By', 'Project Name', 'Created At', 'Seconds to Label', 'External ID', 'Agreement', 'Masks'])
```
Thanks in advance

**Comment by cyrusj89** [comment]
Hello, you can export directly to COCO now in the export tab.

**Comment by intvo** [comment]
@maxsenh Are you able to convert to Coco dataset? we are having the same issue

**Comment by GottliebFreudenreich** [comment]
I'm also facing this issue although in another file.. This error also occurs when trying to convert the exported .json to tfrecord for other datasets with decode_tfrecord_export.py or run_decode.sh

`Traceback (most recent call last):
  File "decode_tfrecord_export.py", line 28, in <module>
    legend = export_json['legend']
TypeError: list indices must be integers or slices, not str
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "decode_tfrecord_export.py", line 28, in <module>
    legend = export_json['legend']
TypeError: list indices must be integers or slices, not str`

@cyrusj89 I can not find the option to export directly to e.g. COCO format in the export tab. Am I missing something?

**Comment by intvo** [comment]
@GottliebFreudenreich Are you using openpose plus or tfpose  to run your dataset?

**Comment by GottliebFreudenreich** [comment]
No actually I'm not using any pose estimation. I'm more interested in semantic segmentation

**Comment by maxsenh** [comment]
Hi! My error at the start of the thread was raised, because I exported the JSON file in XY format. The conversion script labelbox2coco only works with JSON WKT (or well-known-text) format. Exporting it with JSON WKT helped. 

But yes @cyrusj89, for me the export to COCO directly was not given for my data set (biological data, nuclei segmentation, three classes plus background). However, a test data set with given on Labelbox provided the direct export to COCO.
